apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
- ../../base

images:
- name: nginx
  newTag: latest



patchesStrategicMerge:
  - env-vars.yaml

patchesJson6902:
- target:
    version: v2beta2
    kind: HorizontalPodAutoscaler
    name: test-hpa
  path: hpa-patch.yaml
